name: Kernel Update Sentinel
on:
  schedule:
    - cron: '0 */3 * * *' # Memeriksa setiap 3 jam agar Anda tidak tertinggal
  workflow_dispatch:

jobs:
  filter-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Analyze Remote Release
        run: |
          REPO="TheSillyOk/kernel_workflows"
          # Mengambil data release terbaru dari API GitHub
          API_URL="https://api.github.com/repos/$REPO/releases/latest"
          RELEASE_DATA=$(curl -s $API_URL)

          # Logika Filter: Harus mengandung Ginkgo, KSUNext, dan SUSFS
          FILTER_LOGIC='.assets[] | select(.name | contains("Ginkgo") and contains("KSUNext") and contains("SUSFS"))'
          
          DOWNLOAD_URL=$(echo "$RELEASE_DATA" | jq -r "$FILTER_LOGIC | .browser_download_url" | head -n 1)
          FILE_NAME=$(echo "$RELEASE_DATA" | jq -r "$FILTER_LOGIC | .name" | head -n 1)
          TAG_NAME=$(echo "$RELEASE_DATA" | jq -r ".tag_name")

          # Validasi: Jika file tidak ditemukan, hentikan proses agar tidak merusak manifest lama
          if [ "$DOWNLOAD_URL" == "null" ] || [ -z "$DOWNLOAD_URL" ]; then
            echo "Varian target tidak ditemukan pada release ini."
            exit 1
          fi

          # Membuat update.json untuk Franco Kernel Manager
          # Menggunakan stempel waktu (timestamp) sebagai version_number agar FKM mendeteksi sebagai pembaruan
          echo "{
            \"version\": \"$TAG_NAME\",
            \"version_number\": $(date +%Y%m%d%H),
            \"changelog\": \"Update Terdeteksi: $FILE_NAME\",
            \"download_url\": \"$DOWNLOAD_URL\"
          }" > update.json

      - name: Deploy Manifest
        run: |
          git config --local user.email "alice.synthesis@integrity.knight"
          git config --local user.name "Alice Synthesis Thirty"
          git add update.json
          git commit -m "Sentinel: Sinkronisasi kernel varian SUSFS-KSUNext" || exit 0
          git push
